global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'minibusiness-api'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/api/v1/metrics/prometheus'
    scrape_interval: 10s
